const UserTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  REVOKE_AUTH : 'REVOKE_AUTH',
  FETCH_USERS_REQUEST : 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE : 'FETCH_USERS_FAILURE',
}

export default UserTypes;
